### ISSUE TITLE
Error using Melpa stable

### ISSUE THREAD

**Issue by nlamirault** [AshtonKem/Butler#15]
your package can't be installed using Melpa stable : 

Dependency butler failed to install: Need package `deferred-3.1', but only 0.3.2 is available

According to *butler.el* file, dependencies are not valid : 

```lisp
;; Package-Requires: ((deferred "3.2") (json "1.2") (emacs "24"))
```

Last stable version of deferred seems to be 0.3.2

**Comment by AshtonKem** [comment]
Thank you Nicolas, I'm in the middle of a move right now and without Internet, but I'll get to that as soon as possible. 

--Ashton

**Comment by nlamirault** [comment]
Great

**Comment by AshtonKem** [comment]
Nicolas,

It looks like Melpa Stable is being strange. I updated to using deferred 3.2 as of Butler 0.2.3, but Melpa still has the old dep. I have created version 0.2.4 in the hope that a clean build will fix it. 

I'll leave this issue open until it appears to be resolved, and thanks for spotting it.

--
Ashton

**Comment by nlamirault** [comment]
It seems good. 0.2.4 is present in Melpa Stable [1].

[1] : http://stable.melpa.org/#/butler
