### ISSUE TITLE
deferred error

### ISSUE THREAD

**Issue by istib** [AshtonKem/Butler#8]
Running `refresh-butler-status` fails with following error:

``` scheme
    deferred error : (search-failed {)
```

However, everything works fine when stepping through the function with edebug. Seems the following combination is broken:

``` scheme
   (deferred:$ (deferred:url-retrieve (...)
                      (deferred:nextc it (...))
```

**Comment by AlexChesters** [comment]
Hi, I'm getting this issue when using the current version of Butler. I'm using a port other than 80, will this make a difference?
